export const DEFAULT_FORMAT_DATETIME = 'YYYY-MM-DD HH:mm:ss'

export const FILTER_LAST_24_HOUR   = 'last_24_hour'
export const FILTER_TODAY          = 'today'
export const FILTER_YESTERDAY      = 'yesterday'
export const FILTER_LAST_7_DAYS    = 'last_7_days'
export const FILTER_THIS_WEEK      = 'this_week'
export const FILTER_LAST_30_DAYS   = 'last_30_days'
export const FILTER_THIS_MONTH     = 'this_month'
export const FILTER_LAST_6_MONTHS  = 'last_6_months'
export const FILTER_LAST_12_MONTHS = 'last_12_months'
export const FILTER_THIS_YEAR      = 'this_year'

export const GROUP_BY_HOUR  = 'hour'
export const GROUP_BY_DATE  = 'date'
export const GROUP_BY_MONTH = 'month'
